### ISSUE TITLE
Tests fail after initial creation

### ISSUE THREAD

**Issue by redhotvengeance** [jamonholmgren/promotion-template#7]
```bash
promotion new test
cd test
rake spec
```

...will result in 2 failed tests:

```bash
Application 'test'
  - is a ProMotion app

HomeScreen
  - has a navigationController
  - has a right nav bar button [FAILED - nil.kind_of?(UIBarButtonItem) failed]
  - opens the help screen when tapping Help [FAILED - #<HomeScreen:0x11501a0f0>.kind_of?(HelpScreen) failed]

Bacon::Error: nil.kind_of?(UIBarButtonItem) failed
	spec.rb:745:in `satisfy:': HomeScreen - has a right nav bar button
	spec.rb:759:in `method_missing:'
	spec.rb:316:in `block in run_spec_block'
	spec.rb:459:in `execute_block'
	spec.rb:316:in `run_spec_block'
	spec.rb:331:in `run'

Bacon::Error: #<HomeScreen:0x11501a0f0>.kind_of?(HelpScreen) failed
	spec.rb:745:in `satisfy:': HomeScreen - opens the help screen when tapping Help
	spec.rb:759:in `method_missing:'
	spec.rb:316:in `block in run_spec_block'
	spec.rb:459:in `execute_block'
	spec.rb:316:in `run_spec_block'
	spec.rb:331:in `run'

4 specifications (4 requirements), 2 failures, 0 errors
```

I've narrowed down the first error to [this line](https://github.com/jamonholmgren/promotion-template/blob/master/files/spec/screens/home_screen_spec.rb#L12):

`after { @home_screen = nil }`

Commenting that out results in the second `HomeScreen` test passing. I'm still not sure why the third `HomeScreen` test is failing, though I'm still experimenting with it.

**Comment by redhotvengeance** [comment]
...I should add that I'm not advocating that removing `after { @home_screen = nil }` is a solution - in fact, I'm certain it isn't. I was just sharing what I've found after some experimentation.
